dictionaries = ["en_us"]
words = [
    "builtins",
    "dialogs",
    "dif",
    "eslint",
    "fas",
    "fvtt",
    "hbs",
    "xhwfs",
    "xmark",
    "unselected"
]
flag_words = []
ignore_paths = []
