name: Release CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip -r ./fvtt-elemental.zip fvtt-elemental
      - name: Create release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Latest
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'fvtt-elemental/system.json'
          tag: latest