name: Release CI

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python dependencies
        run: pip install plyvel yalm
      - name: Create packs
        run: python3 utils/unpack.py pack
      - name: Create zip file
        run: zip -r ./fvtt-elemental.zip fvtt-elemental
      - name: Create release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Latest
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'fvtt-elemental/system.json, fvtt-elemental.zip'
          tag: latest